[package]
name = "tea"
version = "0.1.0"
edition = "2024"
build = "build/build.rs"

[dependencies]
arrayvec = "0.7.6"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug-assertions = false